### ISSUE TITLE
[Subtask] - dqlang to k6 adapter

### ISSUE THREAD

**Issue by JenSeReal** [dqualizer/dqexec#1]
## User Story

- [ ] user-story one
- [ ] user-story two
- [ ] user-story three

## Dependencies

- Blocked by issue one
- Blocked by issue two

## Additional context

Add any other context or screenshots about the research request here.

**Comment by EddeCCC** [comment]
Implemented here: https://github.com/dqualizer/loadtest-translator-prototype/tree/main/k6-adapter
